version: '3.3'

services:
  laravel:
    build:
      context: .
    ports:
      - "${APP_PORT:-9000}:${APP_PORT:-9000}"
    environment:
      APP_PORT: ${APP_PORT:-9000}
      DB_CONNECTION: mysql
      DB_HOST: db3
      DB_PORT: ${DB_PORT:-3306}
      DB_DATABASE: ${DB_DATABASE:-laravel_db}
      DB_USERNAME: ${DB_USERNAME:-root}
      DB_PASSWORD: ${DB_PASSWORD:-123123}
    depends_on:
      - db3
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${APP_PORT:-9000}"]
      interval: 30s
      timeout: 10s
      retries: 3
      
  db3:
    image: mysql:latest
    ports:
      - "${DB_PORT:-3306}:${DB_PORT:-3306}"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD:-123123}"
      MYSQL_DATABASE: "${DB_DATABASE:-laravel_db}"
    tmpfs:
      - /var/lib/mysql  
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${DB_PASSWORD:-123123}"]
      interval: 5s
      timeout: 20s
      retries: 10
    restart: unless-stopped
